import Foundation

struct Constants {
    
    static let appIconContents = """
                                 {
                                   "images" : [
                                     {
                                       "filename" : "AppIcon.png",
                                       "idiom" : "universal",
                                       "platform" : "ios",
                                       "size" : "1024x1024"
                                     }
                                   ],
                                   "info" : {
                                     "author" : "xcode",
                                     "version" : 1
                                   }
                                 }
                                 """
    
    static let colorSwift = """
                            import SwiftUI
                            
                            extension Color {
                            
                                init(hex: UInt) {
                                    self.init(
                                        .sRGB,
                                        red: Double((hex >> 16) & 0xff) / 255,
                                        green: Double((hex >> 08) & 0xff) / 255,
                                        blue: Double((hex >> 00) & 0xff) / 255,
                                        opacity: 1
                                    )
                                }
                            }
                            """
    
    static func getAppSwift(_ name: String) -> String {
        """
        import SwiftUI
        
        @main
        struct MyApp: App {
            var body: some Scene {
                WindowGroup {
                    \(name)()
                }
            }
        }
        """
    }
    
    static func getPackageSwift(_ name: String) -> String {
        """
        // swift-tools-version: 5.8
        
        // WARNING:
        // This file is automatically generated.
        // Do not edit it by hand because the contents will be replaced.
        
        import PackageDescription
        import AppleProductTypes
        
        let package = Package(
            name: "\(name)",
            platforms: [
                .iOS("16.0")
            ],
            products: [
                .iOSApplication(
                    name: "\(name)",
                    targets: ["AppModule"],
                    displayVersion: "1.0",
                    bundleVersion: "1",
                    appIcon: .asset("AppIcon"),
                    accentColor: .presetColor(.cyan),
                    supportedDeviceFamilies: [
                        .pad,
                        .phone
                    ],
                    supportedInterfaceOrientations: [
                        .portrait,
                        .landscapeRight,
                        .landscapeLeft,
                        .portraitUpsideDown(.when(deviceFamilies: [.pad]))
                    ]
                )
            ],
            targets: [
                .executableTarget(
                    name: "AppModule",
                    path: "."
                )
            ]
        )
        """
    }
    
    static func getContentsJson(_ name: String) -> String {
        """
        {
          "images" : [
            {
              "filename" : "\(name).png",
              "idiom" : "universal",
              "scale" : "1x"
            },
            {
              "idiom" : "universal",
              "scale" : "2x"
            },
            {
              "idiom" : "universal",
              "scale" : "3x"
            }
          ],
          "info" : {
              "author" : "xcode",
              "version" : 1
          }
        }
        """
    }
}
